# ex4 : playing with variables part II
# cmd : ansible-playbook -i inventory.ini 04_playbook_ex4.yaml  --connection=local
- name: play1
  hosts: localhost
  vars:
    servers:
      - nginx
      - apache2
  tasks:
    - name: "Ensure that {{servers[1]}} is installed and up-to-date"
      ansible.builtin.apt: # sudo apt-install servers[1] 
          name: "{{servers[1]}}"
          state: latest
      register: installed # store the output in that variable
    
    - name: "Display {{servers[1]}} installation status"
      debug:
        # display if apt install servers[1] causes any change in your computer 
        # or not (change = an update or install)
        var: installed.changed 
    
    - name: "Check if {{servers[1]}} service is running"
      ansible.builtin.service: 
        name: "{{servers[1]}}"
        state: started
      register: service_status
    
    - name: "Display {{servers[1]}} service status"
      debug:
        var: service_status.state # display the status of server
  