# ex3 : playing with variables
# cmd : ansible-playbook -i inventory.ini 03_playbook_ex3.yaml  --connection=local
- name: play1
  hosts: localhost
  vars:
    server_name: apache2
  tasks:
    - name: "Ensure that {{server_name}} is installed and up-to-date"
      ansible.builtin.apt: # sudo apt-install server_name 
          name: "{{server_name}}"
          state: latest
      register: installed # store the output in that variable
    
    - name: "Display {{server_name}} installation status"
      debug:
        # display if apt install server_name causes any change in your computer 
        # or not (change = an update or install)
        var: installed.changed 
    
    - name: "Check if {{server_name}} service is running"
      ansible.builtin.service: 
        name: "{{server_name}}"
        state: started
      register: service_status
    
    - name: "Display {{server_name}} service status"
      debug:
        var: service_status.state # display the status of server
