# ex5 : when condition illustration ( install nginx )
# cmd : ansible-playbook -i inventory.ini 05_playbook_ex5.yaml  --connection=local
# Note : ansible_os_family is a variable provided by ansible to determine the os family
- name: "Install NGINX on debian or redhat"
  hosts: localhost
  tasks:
    - name: "Install nginx on redhat" # will be skipped
      yum: 
         name: nginx
         state: present
      when: 
        ansible_os_family == "RedHat"
  
    - name: "Install nginx on Debian"
      apt: 
         name: nginx
         state: present
      when: 
        ansible_os_family == "Debian"