# ex2 : check the status of apache2 (systemctl status apache2)
# cmd : ansible-playbook -i inventory.ini 02_playbook_ex2.yaml  --connection=local
- name: play1
  hosts: localhost
  tasks:
    - name: "Ensure that apache2 is installed and up-to-date"
      ansible.builtin.apt: # sudo apt-install apache2 
          name: apache2
          state: latest
      register: installed # store the output in that variable
    
    - name: "Display apache2 installation status"
      debug:
        # display if apt install apache2 causes any change in your computer 
        # or not (change = an update or install)
        var: installed.changed 
    
    - name: "Check if apache2 service is running"
      ansible.builtin.service: 
        name: apache2
        state: started
      register: apache_service_status
    
    - name: "Display apache2 service status"
      debug:
        var: apache_service_status.state # display the status of apache2
