# ex6 : when condition illustration ( install nginx ) with and - or
# cmd : ansible-playbook -i inventory.ini 06_playbook_ex6.yaml  --connection=local
# Note : ansible_os_family is a variable provided by ansible to determine the os family
# and ansible_distribution_version is a variable provided by ansible to determine the os version
- name: "Install NGINX on debian or redhat"
  hosts: localhost
  tasks:
    - name: "Install nginx on redhat" # will be skipped
      yum: 
         name: nginx
         state: present
      when: 
        ansible_os_family == "RedHat" or
        ansible_os_family == "SUSE"
  
    - name: "Install nginx on Debian"
      apt: 
         name: nginx
         state: present
      when: 
        ansible_os_family == "Debian" and
        ansible_distribution_version == '22.04'